"""
Django settings for Libreria project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-bct_kesnk_hf61%xs*&n76)$m5q)u4sa8!*c3ttq$-e^y4xn)6'
DEBUG = True
ALLOWED_HOSTS = ['*']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'login',
    'csp',
    'django_recaptcha',
    'rest_framework',  # Agregado para API REST
]

ROOT_URLCONF = 'Libreria.urls'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'login.middleware.SecurityHeadersMiddleware',
    'login.middleware.RateLimitMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
    'login.middleware.SecurityLoggingMiddleware',
]

TEMPLATES = [
    {   'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Libreria.wsgi.application'

DB_ENGINE = os.environ.get('DB_ENGINE', 'sqlite')

if DB_ENGINE == 'mysql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('DB_NAME', 'libromundo'),
            'USER': os.environ.get('DB_USER', 'root'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'password'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '3306'),
            'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8,}
    },
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
    # Asegúrate de tener este archivo validators.py en tu carpeta Libreria!
    {'NAME': 'Libreria.validators.ComplexPasswordValidator',},
]

LANGUAGE_CODE = 'es-mx' # Cambiado a español para que combine con Libromundo
TIME_ZONE = 'America/Mexico_City'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# --- SEGURIDAD AVANZADA ---
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000', 'http://localhost:8000']

# HSTS
SECURE_HSTS_SECONDS = 31536000  # Recomendado 1 año para producción, 500 está bien para práctica
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# CSP (Content Security Policy)
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ("'self'",),
        'img-src': ("'self'", 'data:'),
        'script-src': (
            "'self'",
            "'unsafe-inline'",
            'https://cdn.jsdelivr.net',
            'https://www.google.com',
            'https://www.gstatic.com',
        ),
        'style-src': (
            "'self'",
            "'unsafe-inline'",
            'https://cdn.jsdelivr.net',
            'https://fonts.googleapis.com',
        ),
        'font-src': (
            "'self'",
            'https://cdn.jsdelivr.net',
            'https://fonts.gstatic.com',
        ),
        'frame-src': (
            "'self'",
            'https://www.google.com',
            'https://www.gstatic.com',
        ),
        'connect-src': (
            "'self'",
            'https://www.google.com',
        ),
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': '%(asctime)s %(levelname)s %(message)s %(ip)s %(user)s %(event_type)s',
        },
        'verbose': {
            'format': '[{asctime}] {levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'security_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'libromundo_security.json'),
            'formatter': 'json',
        },
        'console': {
            'level': 'WARNING',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'libromundo_security': {
            'handlers': ['security_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# --- SEGURIDAD DE SESIONES ---
SESSION_COOKIE_HTTPONLY = True       # Previene acceso a cookie desde JavaScript (XSS)
SESSION_COOKIE_SECURE = False       # True en producción con HTTPS
SESSION_COOKIE_SAMESITE = 'Lax'    # Protección CSRF para cookies
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Sesión expira al cerrar navegador
SESSION_COOKIE_AGE = 3600          # Sesión expira después de 1 hora (segundos)

# --- PROTECCIÓN CSRF ---
CSRF_COOKIE_HTTPONLY = True         # Cookie CSRF no accesible desde JS
CSRF_COOKIE_SECURE = False          # True en producción con HTTPS
CSRF_COOKIE_SAMESITE = 'Lax'

# --- SEGURIDAD ADICIONAL ---
SECURE_BROWSER_XSS_FILTER = True    # Header X-XSS-Protection
X_FRAME_OPTIONS = 'DENY'           # Previene clickjacking

# Proxy confiable: solo confiar en X-Forwarded-For si hay un reverse proxy configurado.
# En desarrollo sin proxy, usar False para evitar spoofing de IP.
USE_X_FORWARDED_FOR = False

# reCAPTCHA settings
RECAPTCHA_PUBLIC_KEY = os.environ.get('RECAPTCHA_PUBLIC_KEY', '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI')  # Test key
RECAPTCHA_PRIVATE_KEY = os.environ.get('RECAPTCHA_PRIVATE_KEY', '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe')  # Test key

SILENCED_SYSTEM_CHECKS = ['django_recaptcha.recaptcha_test_key_error']

# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'tu-email@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'tu-password')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER